### ISSUE TITLE
Idea of an effective and simple feature 

### ISSUE THREAD

**Issue by ghost** [macie-k/remove-ghost-followers#1]
Hey, something came to my mind a couple of hours ago.
I think 40% of your users are  comfortable with bots, insights or scrapers.
As your script remove the followers, not blocking them (am I right ?), can't we give a list of users or account IDs to the script and let it remove one by one the followers from the given list instead of scraping ?
Anyway, your are doing a great job and thanks for your script :)

**Comment by macie-k** [comment]
Hi, sounds great, thanks for the suggestion.
I created it with the intend of detecting and removing bots, rather than just removing followers.
But I will look into it in the near future.

**Comment by ghost** [comment]
Someone told me about your script and the wanted function the following:
 "looks like you can just set "not_likers" to the list of users to remove. Specifically, bot.remove_follower method"
I'm not into third party integrations yet with Python, so I can't tell if it is 100% doable.

Yeah, thing is I did scrap my followers having 1200+ of followings, with no profile pic or inactive for a 2 yrs and more.
I did remove manually about 230 accounts, I have a 400% regrowth of my reach, which is far from my original statistics before my 1yr period posting stories only.

**Comment by macie-k** [comment]
I added the `--list` `-l` parameter that takes a filename as an argument.
Provided you have a list of either IDs or usernames in a file called `users.txt` you can remove them by launching the script like that:
```
python remove_ghosts.py --list users.txt
```

**Comment by ghost** [comment]
This is awesome, it works perfectly ! Thanks a heap mate 👍 
Just a question, I've been seeking for the delay code in Instabot's script and yours as well, i ended up finding nothing about a code allowing to change the delay between the actions/removals ... Do ya know where that is ?

**Comment by macie-k** [comment]
There is actually a small delay at the 96th line: `sleep(.3)` if you wish to wait longer just change the number in the parentheses
