### ISSUE TITLE
it won't let me write my password

### ISSUE THREAD

**Issue by iApoloMC** [macie-k/remove-ghost-followers#5]
![image](https://user-images.githubusercontent.com/39244653/153932782-5dc8fdb6-c86a-4363-9cbd-e5e0ad86f058.png)
Hello, the .exe keeps saying this and I can't write my password, any way to fix it? Thanks!!

**Comment by macie-k** [comment]
It's [instabot](https://github.com/ohld/igbot)'s fault, can't help you sorry.
