### ISSUE TITLE
Error 429!

### ISSUE THREAD

**Issue by thsofia** [macie-k/remove-ghost-followers#7]
ERROR - Request returns 429 error!
WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
ERROR - Request returns 429 error
WARNING - That means 'too many requests'. I'll go to sleep for 10 minutes.
ERROR - Request returns 429 error
WARNING - That means 'too many requests'. I'll go to sleep for 15 minutes.

Do you have any idea how this can be fixed?

**Comment by macie-k** [comment]
As the error says: too many requests, wait an hour or two, or a day and try again.
With big amount of posts this will persist.

**Comment by thsofia** [comment]
I have 6 posts in total in this account and just 29 followers. It does not make sense. I try again one day later and gives me error 400. Also gives me Instragram’s error message: challenge_required. :(

**Comment by macie-k** [comment]
Challenge required means 2 factor authentication (your SMS code).

And about the other errors, this is an old script, the API library I used is already archived, instagram is constantly making it harder to create any sort of bots, so it is possible that they just disabled something. Especially the 400 error which stands for `Bad request`. I'm sorry but I can't really help.
